color0 #d1bdbf
color1 #cd021d
color2 #b2343d
color3 #8e5932
color4 #6d6724
color5 #71282d
color6 #6f472a
color7 #1b1819
color8 #917d7f
color9 #cd021d
color10 #b2343d
color11 #8e5932
color12 #6d6724
color13 #71282d
color14 #6f472a
color15 #1b1819

cursor                #1b1819
cursor_text_color     #eae1e2
background            #eae1e2
foreground            #1b1819
selection_foreground  #574e4f
selection_background  #d1bdbf
active_border_color   #b2343d
inactive_border_color #d1bdbf
url_color             #b2343d

active_tab_foreground   #faf9fa
active_tab_background   #b2343d
inactive_tab_foreground #574e4f
inactive_tab_background #d1bdbf
cursor_trail_color      #574e4f
