color0 #d1cdbd
color1 #d10441
color2 #796800
color3 #55720c
color4 #3a752f
color5 #716528
color6 #586f2a
color7 #1b1a18
color8 #888674
color9 #d10441
color10 #796800
color11 #55720c
color12 #3a752f
color13 #716528
color14 #586f2a
color15 #1b1a18

cursor                #1b1a18
cursor_text_color     #eae8e1
background            #eae8e1
foreground            #1b1a18
selection_foreground  #595751
selection_background  #d1cdbd
active_border_color   #a9973c
inactive_border_color #d1cdbd
url_color             #a9973c

active_tab_foreground   #303030
active_tab_background   #a9973c
inactive_tab_foreground #595751
inactive_tab_background #d1cdbd
cursor_trail_color      #595751
