color0 #bdc6d1
color1 #cd003f
color2 #1d3c63
color3 #221f51
color4 #37204a
color5 #284871
color6 #2e2a6f
color7 #18191b
color8 #7b838f
color9 #cd003f
color10 #1d3c63
color11 #221f51
color12 #37204a
color13 #284871
color14 #2e2a6f
color15 #18191b

cursor                #18191b
cursor_text_color     #e1e5ea
background            #e1e5ea
foreground            #18191b
selection_foreground  #4f5257
selection_background  #bdc6d1
active_border_color   #1d3c63
inactive_border_color #bdc6d1
url_color             #1d3c63

active_tab_foreground   #f9fafa
active_tab_background   #1d3c63
inactive_tab_foreground #4f5257
inactive_tab_background #bdc6d1
cursor_trail_color      #4f5257
